name = "Delphinus"
license = "MIT"
licenselink = "https://github.com/yourname/delphinus-hugo/blob/master/LICENSE"
description = "A Hugo theme using Aarhus University's Delphinus Design System"
homepage = "https://delphinus.au.dk/"
min_version = "0.112.0"

[author]
  name = "Your Name"
  homepage = "https://example.org"
