baseURL = 'https://example.org/'
languageCode = 'da'
title = 'Mit AU Site'

[params]
  siteName = "Mit AU Site"
  description = "En Hugo site baseret p√• AU Delphinus Designsystem"
  # Skift til "en" for engelsk
  language = "da"

[menu]
  [[menu.main]]
    name = "Forside"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Om os"
    url = "/om/"
    weight = 2
  [[menu.main]]
    name = "Nyheder"
    url = "/nyheder/"
    weight = 3
  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
