baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Delphinus Documentation'
theme = 'delphinus'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Documentation site using Aarhus University's Delphinus Design System"
